# Параметры для ML пайплайна
# Этот файл содержит все настраиваемые параметры для ML пайплайна анализа научных публикаций

# Параметры инженерии признаков
feature_engineering:
  tfidf_max_features: 5000
  ngram_range: [1, 2] # Используем униграммы и биграммы
  min_df: 2 # Минимальная частота документа
  max_df: 0.95 # Максимальная частота документа
  use_tfidf: true
  lowercase: true
  stop_words: "english"

  # Обработка текста
  text_columns:
    - "title_cleaned"
    - "abstract_cleaned"
    - "keywords"

  # Кодирование категориальных признаков
  categorical_columns:
    - "journal_category"
    - "abstract_category"
    - "citation_category"

  # Числовые признаки
  numerical_columns:
    - "impact_score"
    - "cited_by"
    - "year"
    - "title_length"
    - "abstract_length"
    - "author_count"
    - "num_keywords"

# Параметры обучения модели
train:
  algorithm: "RandomForestClassifier" # Варианты: RandomForestClassifier, SVM, LogisticRegression
  test_size: 0.2
  random_state: 42

  # Кросс-валидация
  cross_validation:
    folds: 3
    scoring: "accuracy"

  # Специфичные параметры модели
  random_forest:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 5
    min_samples_leaf: 2
    max_features: "sqrt"
    bootstrap: true
    oob_score: true

  svm:
    kernel: "rbf"
    C: 1.0
    gamma: "scale"
    probability: true

  logistic_regression:
    penalty: "l2"
    C: 1.0
    max_iter: 1000
    solver: "liblinear"

# Параметры оценки модели
evaluate:
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1_score"
    - "roc_auc"

  # Цель классификации
  target_column: "journal_category"

  # Настройки визуализации
  plot_style: "seaborn"
  figure_size: [10, 8]
  dpi: 300

  # Настройки отчета
  include_classification_report: true
  include_confusion_matrix: true
  include_feature_importance: true
  top_features_to_show: 20

# Параметры валидации данных
data_validation:
  # Ожидаемые пороги качества данных
  min_completeness: 0.95
  max_missing_ratio: 0.05

  # Ожидаемые диапазоны данных
  year_range: [2020, 2024]
  min_citations: 0
  max_citations: 1000

  # Валидация текстовых полей
  min_title_length: 10
  max_title_length: 500
  min_abstract_length: 50
  max_abstract_length: 2000

# Параметры отслеживания MLflow
mlflow:
  experiment_name: "research_publications_classification"
  run_name: "baseline_model"
  tracking_uri: "file:./mlruns"

  # Теги
  tags:
    project: "research_agents_hub"
    domain: "digital_pathology"
    model_type: "classification"
    data_version: "v1.0"

  # Артефакты для логирования
  log_artifacts:
    - "models/"
    - "reports/"
    - "data/processed/processing_metadata.yaml"

# Настройки воспроизводимости
reproducibility:
  seed: 42
  deterministic: true

# Настройки ресурсов
resources:
  n_jobs: -1 # Использовать все доступные ядра
  memory_limit: "4G"
