# Параметры для ML пайплайна
# Этот файл содержит все настраиваемые параметры для ML пайплайна анализа научных публикаций

# Параметры инженерии признаков
feature_engineering:
  tfidf_max_features: 5000
  ngram_range: [1, 2] # Используем униграммы и биграммы
  min_df: 2 # Минимальная частота документа
  max_df: 0.95 # Максимальная частота документа
  use_tfidf: true
  lowercase: true
  stop_words: "english"

  # Обработка текста
  text_columns:
    - "title_cleaned"
    - "abstract_cleaned"
    - "keywords"

  # Кодирование категориальных признаков
  categorical_columns:
    - "journal_category"
    - "abstract_category"
    - "citation_category"

  # Числовые признаки
  numerical_columns:
    - "impact_score"
    - "cited_by"
    - "year"
    - "title_length"
    - "abstract_length"
    - "author_count"
    - "num_keywords"

# Параметры обучения модели
train:
  algorithm: "RandomForestClassifier" # Варианты: RandomForestClassifier, SVM, LogisticRegression
  test_size: 0.2
  random_state: 42

  # Кросс-валидация
  cross_validation:
    folds: 3
    scoring: "accuracy"

  # Специфичные параметры модели
  random_forest:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 5
    min_samples_leaf: 2
    max_features: "sqrt"
    bootstrap: true
    oob_score: true

  svm:
    kernel: "rbf"
    C: 1.0
    gamma: "scale"
    probability: true

  logistic_regression:
    penalty: "l2"
    C: 1.0
    max_iter: 1000
    solver: "liblinear"

# Параметры оценки модели
evaluate:
  dpi: 300
  figure_size:
  - 10
  - 8
  include_classification_report: true
  include_confusion_matrix: true
  include_feature_importance: true
  metrics:
  - accuracy
  - precision
  - recall
  - f1_score
  - roc_auc
  plot_style: seaborn
  target_column: journal_category
  top_features_to_show: 20
feature_engineering:
  categorical_columns:
  - journal_category
  - abstract_category
  - citation_category
  lowercase: true
  max_df: 0.95
  min_df: 2
  ngram_range:
  - 1
  - 2
  numerical_columns:
  - impact_score
  - cited_by
  - year
  - title_length
  - abstract_length
  - author_count
  - num_keywords
  stop_words: english
  text_columns:
  - title_cleaned
  - abstract_cleaned
  - keywords
  tfidf_max_features: 5000
  use_tfidf: true
mlflow:
  experiment_name: research_publications_classification
  log_artifacts:
  - models/
  - reports/
  - data/processed/processing_metadata.yaml
  run_name: baseline_model
  tags:
    data_version: v1.0
    domain: digital_pathology
    model_type: classification
    project: research_agents_hub
  tracking_uri: file:./mlruns
reproducibility:
  deterministic: true
  seed: 42
resources:
  memory_limit: 4G
  n_jobs: -1
train:
  algorithm: RandomForestClassifier
  cross_validation:
    folds: 3
    scoring: accuracy
  logistic_regression:
    C: 1.0
    max_iter: 1000
    penalty: l2
    solver: liblinear
  random_forest:
    bootstrap: true
    max_depth: 10
    max_features: sqrt
    min_samples_leaf: 2
    min_samples_split: 5
    n_estimators: 100
    oob_score: true
  random_state: 42
  svm:
    C: 1.0
    gamma: scale
    kernel: rbf
    probability: true
  test_size: 0.2
